name: api_communications
description: Una forma facil de consumir un API de Soluciones Nerus.

version: 1.0.3
repository: https://github.com/solunerus/api_communications.git

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.22.0

  flutter_lints: ^3.0.1

flutter:
  # assets:
  #   - /Users/developer/developer/code/flutter/environment/.env
