name: api_communications
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
      sdk: flutter
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.22.0

  flutter_lints: ^2.0.1
