name: api_communications
description: Una forma facil de consumir un API de Soluciones Nerus.

version: 1.0.0
repository: https://github.com/solunerus/api_communications.git

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
      sdk: flutter
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.22.0

  flutter_lints: ^2.0.1

flutter:
  assets:
    - /Users/developer/developer/code/flutter/environment/.env
